apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: your-root-password
  MYSQL_DATABASE: your-database-name
  MYSQL_USER: your-username
  MYSQL_PASSWORD: your-user-password
