apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: nginx-service
    app: java-web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx-deployment
    app: java-web-app
  type: ClusterIP
status:
  loadBalancer: {}
