apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: tomcat-service
    app: java-web-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30006
  selector:
    name: tomcat-deployment
    app: java-web-app
status:
  loadBalancer: {}
